export type Poster = {
  alt: string;
  description: string;
  slug: string;
  src: string;
  title: string;
};

export const posters: Poster[] = [
  {
    src: "/cozydesigns/portfolio-assets/dd276a8e-the-world-is-yours-poster.webp",
    alt: "Mama Said Knock You Out poster",
    slug: "mama-said-knock-you-out",
    title: "Mama Said Knock You Out",
    description: "LL Cool J",
  },
  {
    src: "/cozydesigns/portfolio-assets/2ee98352-mamma-said-artwork.webp",
    alt: "Don't be Dumb poster",
    slug: "dont-be-dumb",
    title: "Don't be Dumb",
    description: "A$AP Rocky",
  },
  {
    src: "/cozydesigns/portfolio-assets/4cb864e0-scaring-the-hoes-poster.webp",
    alt: "The World Is Yours poster",
    slug: "the-world-is-yours",
    title: "The World Is Yours",
    description: "Nas",
  },
  {
    src: "/cozydesigns/portfolio-assets/b970b43c-ny-state-of-mind-poster.webp",
    alt: "N.Y. State of Mind poster",
    slug: "ny-state-of-mind",
    title: "N.Y. State of Mind",
    description: "Nas",
  },
  {
    src: "/cozydesigns/portfolio-assets/8df4ebb8-illustrated-portrait-poster.webp",
    alt: "The Emperor's New Clothes poster",
    slug: "the-emperors-new-clothes",
    title: "The Emperor’s New Clothes",
    description: "Raekwon",
  },
  {
    src: "/cozydesigns/portfolio-assets/e88b4545-raekwon-poster.webp",
    alt: "GNX poster",
    slug: "gnx",
    title: "GNX",
    description: "Kendrick Lamar",
  },
  {
    src: "/cozydesigns/portfolio-assets/70d5909b-no-feelings-poster.webp",
    alt: "Juvenile Hell poster",
    slug: "juvenile-hell",
    title: "Juvenile Hell",
    description: "Mobb Deep",
  },
  {
    src: "/cozydesigns/portfolio-assets/32f03200-joker-poster.webp",
    alt: "The Infamous poster",
    slug: "the-infamous",
    title: "The Infamous",
    description: "Mobb Deep",
  },
  {
    src: "/cozydesigns/portfolio-assets/a4c92f9b-gnx-poster.webp",
    alt: "ICON poster",
    slug: "icon",
    title: "ICON",
    description: "Brent Faiyaz",
  },
  {
    src: "/cozydesigns/portfolio-assets/7a570fbb-jay-z-artwork.webp",
    alt: "Hell On Earth poster",
    slug: "hell-on-earth",
    title: "Hell On Earth",
    description: "Mobb Deep",
  },
  {
    src: "/cozydesigns/portfolio-assets/f90ecbd9-the-infamous-artwork.webp",
    alt: "Romancham poster",
    slug: "romancham",
    title: "Romancham",
    description: "Jithu Madhavan",
  },
  {
    src: "/cozydesigns/portfolio-assets/61ab69fa-hell-on-earth-poster.webp",
    alt: "Joker: Folie a Deux poster",
    slug: "joker-folie-a-deux",
    title: "Joker: Folie à Deux",
    description: "Todd Phillips",
  },
  {
    src: "/cozydesigns/portfolio-assets/b09b2cca-jackboys-ii-poster.webp",
    alt: "Sinners poster",
    slug: "sinners",
    title: "Sinners",
    description: "Ryan Coogler",
  },
  {
    src: "/cozydesigns/portfolio-assets/b5b88675-coon-poster.webp",
    alt: "Hurry Up Tomorrow poster",
    slug: "hurry-up-tomorrow",
    title: "Hurry Up Tomorrow",
    description: "The Weeknd",
  },
  {
    src: "/cozydesigns/portfolio-assets/b61e1e21-harlem-finest-poster.webp",
    alt: "JACKBOYS II poster",
    slug: "jackboys-ii",
    title: "JACKBOYS II",
    description: "Travis Scott & JACKBOYS",
  },
  {
    src: "/cozydesigns/portfolio-assets/2c6d903d-problem-artwork.webp",
    alt: "Harlem's Finest poster",
    slug: "harlems-finest",
    title: "Harlem’s Finest",
    description: "Big L",
  },
  {
    src: "/cozydesigns/portfolio-assets/a61748ff-d-angelo-artwork.webp",
    alt: "Don't Tap The Glass poster",
    slug: "dont-tap-the-glass",
    title: "Don’t Tap The Glass",
    description: "Tyler, The Creator",
  },
  {
    src: "/cozydesigns/portfolio-assets/e8e8aa22-die-with-a-smile-poster.webp",
    alt: "Chromakopia poster",
    slug: "chromakopia",
    title: "Chromakopia",
    description: "Tyler, The Creator",
  },
  {
    src: "/cozydesigns/portfolio-assets/982062e4-hurry-up-tomorrow-poster.webp",
    alt: "Brown Sugar poster",
    slug: "brown-sugar",
    title: "Brown Sugar",
    description: "D’Angelo",
  },
  {
    src: "/cozydesigns/portfolio-assets/35588c2a-hypnophobia-poster.webp",
    alt: "LIT EFFECT poster",
    slug: "lit-effect",
    title: "LIT EFFECT",
    description: "Denzel Curry",
  },
  {
    src: "/cozydesigns/portfolio-assets/71547230-sinners-poster.webp",
    alt: "Not Like Us poster",
    slug: "not-like-us",
    title: "Not Like Us",
    description: "Kendrick Lamar",
  },
  {
    src: "/cozydesigns/portfolio-assets/4027a17f-nyy-eyes-poster.webp",
    alt: "The Coming poster",
    slug: "the-coming",
    title: "The Coming",
    description: "Busta Rhymes",
  },
  {
    src: "/cozydesigns/portfolio-assets/da0f8c6b-the-glass-poster.webp",
    alt: "APT. poster",
    slug: "apt",
    title: "APT.",
    description: "ROSÉ & Bruno Mars",
  },
  {
    src: "/cozydesigns/portfolio-assets/0700839a-rose-poster.webp",
    alt: "MY EYES poster",
    slug: "my-eyes",
    title: "MY EYES",
    description: "Travis Scott",
  },
  {
    src: "/cozydesigns/portfolio-assets/3a7bf456-messiah-poster.webp",
    alt: "Dies Irae poster",
    slug: "dies-irae",
    title: "Dies Irae",
    description: "Rahul Sadasivan",
  },
  {
    src: "/cozydesigns/portfolio-assets/515326e1-dies-irae-poster.webp",
    alt: "Naranga Paal poster",
    slug: "naranga-paal",
    title: "Naranga Paal",
    description: "Gabri",
  },
  {
    src: "/cozydesigns/portfolio-assets/05a793a7-retro-comic-poster.webp",
    alt: "Scaring The Hoes poster",
    slug: "scaring-the-hoes",
    title: "Scaring The Hoes",
    description: "JPEGMAFIA & Danny Brown",
  },
];
